//! Hooks the iced window's WndProc to:
//!   - Detect modal message loops (drag/resize/menu) and pause mpv during them.
//!   - Snap the window to monitor edges during drag (WM_MOVING).
//!   - Snap the window to *other MPV-NE windows* during drag, like PotPlayer
//!     does with multiple instances open - an edge touches the nearest
//!     sibling window's opposite edge (docking side-by-side / stacked).
//!     Siblings are identified by window class name (all MPV-NE windows
//!     share one, generated by winit/iced) rather than process name, so no
//!     process-query APIs are needed. Only considered when the windows
//!     overlap on the perpendicular axis, so it never snaps across the
//!     whole screen to an unrelated window.
//!
//! Uses old-style SetWindowLongPtrW subclassing - no comctl32 v6 / manifest
//! requirement, works on all Windows versions.
#![cfg(target_os = "windows")]

use std::sync::{Mutex, OnceLock};
use std::sync::atomic::{AtomicBool, AtomicI32, AtomicI64, AtomicIsize, AtomicU8, Ordering};
use std::time::Duration;

type Callback = Box<dyn Fn() + Send + Sync>;

static ON_ENTER:    OnceLock<Callback> = OnceLock::new();
static ON_EXIT:     OnceLock<Callback> = OnceLock::new();
static INSTALLED:   AtomicBool  = AtomicBool::new(false);
/// Original WndProc saved by SetWindowLongPtrW; we chain to it for every
/// message we do not handle ourselves.
static ORIG_WNDPROC: AtomicIsize = AtomicIsize::new(0);

type HWND     = isize;
type HMONITOR = isize;

#[repr(C)]
#[derive(Clone, Copy)]
struct RECT { left: i32, top: i32, right: i32, bottom: i32 }

#[repr(C)]
struct POINT { x: i32, y: i32 }

#[repr(C)]
struct MONITORINFO {
    cb_size:    u32,
    rc_monitor: RECT,
    rc_work:    RECT,
    dw_flags:   u32,
}

const GWLP_WNDPROC: i32 = -4;

#[link(name = "user32")]
unsafe extern "system" {
    fn EnumWindows(cb: unsafe extern "system" fn(HWND, isize) -> i32, l: isize) -> i32;
    fn GetWindowThreadProcessId(hwnd: HWND, pid: *mut u32) -> u32;
    fn GetCurrentProcessId() -> u32;
    fn IsWindowVisible(hwnd: HWND) -> i32;
    fn GetWindow(hwnd: HWND, cmd: u32) -> HWND;
    fn SetWindowLongPtrW(hwnd: HWND, index: i32, new_val: isize) -> isize;
    fn CallWindowProcW(prev: isize, hwnd: HWND, msg: u32, w: usize, l: isize) -> isize;
    fn MonitorFromRect(rc: *const RECT, flags: u32) -> HMONITOR;
    fn GetMonitorInfoW(mon: HMONITOR, mi: *mut MONITORINFO) -> i32;
    fn GetDpiForWindow(hwnd: HWND) -> u32;
    fn GetCursorPos(pt: *mut POINT) -> i32;
    fn GetClassNameW(hwnd: HWND, buf: *mut u16, max_count: i32) -> i32;
    fn GetWindowRect(hwnd: HWND, rect: *mut RECT) -> i32;
}

const GW_OWNER:                u32 = 4;
const MONITOR_DEFAULTTONEAREST: u32 = 2;
const WM_ENTERMENULOOP: u32 = 0x0211;
const WM_EXITMENULOOP:  u32 = 0x0212;
const WM_ENTERSIZEMOVE: u32 = 0x0231;
const WM_EXITSIZEMOVE:  u32 = 0x0232;
const WM_MOVING:        u32 = 0x0216;
/// Distance (logical px at 96 DPI) to attract to an edge.
const SNAP_IN_PX:  i32 = 10;
/// Euclidean cursor displacement required to release a snapped edge.
/// Must satisfy: SNAP_OUT_PX * cos(max_expected_drag_angle) > SNAP_IN_PX,
/// otherwise the window edge lands back inside snap_in after release and
/// immediately re-snaps. At 60° drag angle: 22 * cos(60°) = 11 > 10. ✓
const SNAP_OUT_PX: i32 = 22;

// ---------------------------------------------------------------------------
// EnumWindows callback - finds our main window by process ID
// ---------------------------------------------------------------------------

static FOUND_HWND: AtomicIsize = AtomicIsize::new(0);

/// Per-edge snap state: stores the cursor position (x,y) at snap time packed
/// into an i64 (high 32 = x, low 32 = y), or i64::MIN when not snapped.
/// Snap-in uses window-edge distance; snap-out uses Euclidean cursor
/// displacement from the snap point so diagonal drags release equally well.
static SNAP_L: AtomicI64 = AtomicI64::new(i64::MIN);
static SNAP_R: AtomicI64 = AtomicI64::new(i64::MIN);
static SNAP_T: AtomicI64 = AtomicI64::new(i64::MIN);
static SNAP_B: AtomicI64 = AtomicI64::new(i64::MIN);
/// Per-edge release guard: counts down WM_MOVING frames after a snap releases,
/// blocking immediate re-snap. Without this, releasing at a shallow angle leaves
/// the window edge still within snap_in, causing a wiggle-snap on the next frame.
static GUARD_L: AtomicU8 = AtomicU8::new(0);
static GUARD_R: AtomicU8 = AtomicU8::new(0);
static GUARD_T: AtomicU8 = AtomicU8::new(0);
static GUARD_B: AtomicU8 = AtomicU8::new(0);
/// The target position an edge locked onto at the moment it snapped. While
/// snapped, this frozen value is reused every frame instead of whatever
/// closest_target picks that frame - near a corner, an abut candidate and an
/// align candidate can both be within snap_in at once, and picking "whichever
/// is closest" fresh each frame let the applied position flip silently
/// between the two even while nominally still snapped (no release/re-engage
/// event, just a jittering position) - this is what "still bugginess" traced
/// back to.
static SNAP_TARGET_L: AtomicI32 = AtomicI32::new(0);
static SNAP_TARGET_R: AtomicI32 = AtomicI32::new(0);
static SNAP_TARGET_T: AtomicI32 = AtomicI32::new(0);
static SNAP_TARGET_B: AtomicI32 = AtomicI32::new(0);

fn pack_pt(x: i32, y: i32) -> i64 { ((x as i64) << 32) | (y as u32 as i64) }
fn unpack_pt(v: i64) -> (i32, i32) { ((v >> 32) as i32, v as i32) }
// Only the perpendicular axis counts toward release — sliding along an edge
// must never loosen the snap.
fn x_disp(snap_pt: i64, cur_x: i32) -> i32 { let (sx, _) = unpack_pt(snap_pt); (cur_x - sx).abs() }
fn y_disp(snap_pt: i64, cur_y: i32) -> i32 { let (_, sy) = unpack_pt(snap_pt); (cur_y - sy).abs() }

// ---------------------------------------------------------------------------
// Sibling window tracking - other MPV-NE instances to snap against
// ---------------------------------------------------------------------------

/// Our own hwnd (set at install time) - excluded when enumerating siblings.
static OWN_HWND: AtomicIsize = AtomicIsize::new(0);
/// Our own window class name, used to recognise sibling MPV-NE windows
/// without needing process-name queries.
static OWN_CLASS: OnceLock<String> = OnceLock::new();
/// Rects of other visible MPV-NE windows, refreshed once per drag
/// (WM_ENTERSIZEMOVE) rather than on every WM_MOVING for efficiency.
static SIBLING_RECTS: Mutex<Vec<RECT>> = Mutex::new(Vec::new());

fn get_class_name(hwnd: HWND) -> Option<String> {
    let mut buf = [0u16; 256];
    let len = unsafe { GetClassNameW(hwnd, buf.as_mut_ptr(), buf.len() as i32) };
    if len <= 0 { return None; }
    Some(String::from_utf16_lossy(&buf[..len as usize]))
}

unsafe extern "system" fn enum_siblings_cb(hwnd: HWND, _: isize) -> i32 {
    if hwnd == OWN_HWND.load(Ordering::Relaxed) { return 1; }
    if unsafe { IsWindowVisible(hwnd) } == 0    { return 1; }
    // Skip owned windows (our own menu popup, tooltips, etc.) on both our
    // window and any sibling's - none of those should be snap targets.
    if unsafe { GetWindow(hwnd, GW_OWNER) } != 0 { return 1; }
    let Some(class) = get_class_name(hwnd) else { return 1; };
    if Some(&class) != OWN_CLASS.get() { return 1; }
    let mut rect = RECT { left: 0, top: 0, right: 0, bottom: 0 };
    if unsafe { GetWindowRect(hwnd, &mut rect) } == 0 { return 1; }
    if let Ok(mut v) = SIBLING_RECTS.lock() { v.push(rect); }
    1 // keep enumerating - collect every sibling, not just the first
}

/// True if the two rects overlap on Y, padded by `tol` on each side so
/// windows that are *about to* overlap (approaching a shared corner) count
/// too - without this, corner-to-corner snapping never registers, because
/// right at a corner neither axis has genuine overlap yet, only the moment
/// they'd touch (which is exactly when we want the candidate to exist).
fn near_y(a: &RECT, b: &RECT, tol: i32) -> bool {
    a.top - tol < b.bottom && b.top - tol < a.bottom
}
/// Same as `near_y` but for the X axis (candidates for top/bottom snapping).
fn near_x(a: &RECT, b: &RECT, tol: i32) -> bool {
    a.left - tol < b.right && b.left - tol < a.right
}

/// Picks whichever candidate position (monitor edge, or one of `extra`) is
/// closest to `my_val`, returning (target position, distance).
fn closest_target(my_val: i32, monitor_val: i32, extra: &[i32]) -> (i32, i32) {
    let mut best = monitor_val;
    let mut best_dist = (my_val - monitor_val).abs();
    for &c in extra {
        let d = (my_val - c).abs();
        if d < best_dist {
            best = c;
            best_dist = d;
        }
    }
    (best, best_dist)
}

unsafe extern "system" fn enum_cb(hwnd: HWND, _: isize) -> i32 {
    let mut pid = 0u32;
    unsafe { GetWindowThreadProcessId(hwnd, &mut pid) };
    if pid != unsafe { GetCurrentProcessId() } { return 1; }
    if unsafe { IsWindowVisible(hwnd) } == 0    { return 1; }
    if unsafe { GetWindow(hwnd, GW_OWNER) } != 0 { return 1; }
    FOUND_HWND.store(hwnd, Ordering::SeqCst);
    0 // stop
}

// ---------------------------------------------------------------------------
// Our replacement WndProc
// ---------------------------------------------------------------------------

unsafe extern "system" fn wnd_proc(hwnd: HWND, msg: u32, w: usize, l: isize) -> isize {
    match msg {
        WM_ENTERMENULOOP => {
            // Pause mpv during native menu loops - they block iced's event loop
            // completely so frames can't be presented anyway.
            if let Some(cb) = ON_ENTER.get() { cb(); }
        }
        WM_EXITMENULOOP => {
            if let Some(cb) = ON_EXIT.get() { cb(); }
        }
        WM_ENTERSIZEMOVE => {
            // Refresh the sibling window list once per drag rather than on
            // every WM_MOVING - EnumWindows is cheap but there's no reason
            // to repeat it dozens of times per second during a drag when
            // other windows can't move out from under us mid-drag anyway.
            if let Ok(mut v) = SIBLING_RECTS.lock() {
                v.clear();
            }
            unsafe { EnumWindows(enum_siblings_cb, 0) };
        }
        WM_EXITSIZEMOVE => {
            // Reset all snap state when drag ends.
            SNAP_L.store(i64::MIN, Ordering::Relaxed);
            SNAP_R.store(i64::MIN, Ordering::Relaxed);
            SNAP_T.store(i64::MIN, Ordering::Relaxed);
            SNAP_B.store(i64::MIN, Ordering::Relaxed);
            GUARD_L.store(0, Ordering::Relaxed);
            GUARD_R.store(0, Ordering::Relaxed);
            GUARD_T.store(0, Ordering::Relaxed);
            GUARD_B.store(0, Ordering::Relaxed);
        }
        WM_MOVING => {
            let r = unsafe { &mut *(l as *mut RECT) };
            let width  = r.right  - r.left;
            let height = r.bottom - r.top;

            let dpi     = unsafe { GetDpiForWindow(hwnd) }.max(96);
            let snap_in  = (SNAP_IN_PX  * dpi as i32) / 96;
            let snap_out = (SNAP_OUT_PX * dpi as i32) / 96;

            let mut mi = MONITORINFO {
                cb_size:    std::mem::size_of::<MONITORINFO>() as u32,
                rc_monitor: RECT { left: 0, top: 0, right: 0, bottom: 0 },
                rc_work:    RECT { left: 0, top: 0, right: 0, bottom: 0 },
                dw_flags:   0,
            };
            let hmon = unsafe { MonitorFromRect(r as *const RECT, MONITOR_DEFAULTTONEAREST) };
            if hmon != 0 { unsafe { GetMonitorInfoW(hmon, &mut mi) }; }
            let wa = &mi.rc_work;

            // Build per-edge candidate lists from sibling windows, like
            // PotPlayer's multi-instance snap: abutting (this edge touches
            // their opposite edge, for docking side-by-side) and aligning
            // (this edge matches their same edge, for lining up corners
            // while stacked). Each is gated by the *opposite* axis's
            // proximity rather than both by the same one - abut only when
            // approaching from the side (Y-proximity), align only when
            // already roughly stacked (X-proximity). That keeps them from
            // competing for the same edge during a plain side-on approach;
            // both only apply together right at a shared corner (where
            // near_x and near_y both hold, by design of the padding), which
            // is exactly when both axes should catch at once.
            let siblings = SIBLING_RECTS.lock().map(|v| v.clone()).unwrap_or_default();
            let mut cand_l = Vec::new();
            let mut cand_r = Vec::new();
            let mut cand_t = Vec::new();
            let mut cand_b = Vec::new();
            for s in &siblings {
                if near_y(r, s, snap_in) {
                    cand_l.push(s.right); // abut: our left touches their right
                    cand_r.push(s.left);  // abut: our right touches their left
                }
                if near_x(r, s, snap_in) {
                    cand_l.push(s.left);  // align: our left matches their left
                    cand_r.push(s.right); // align: our right matches their right
                }
                if near_x(r, s, snap_in) {
                    cand_t.push(s.bottom); // abut: our top touches their bottom
                    cand_b.push(s.top);    // abut: our bottom touches their top
                }
                if near_y(r, s, snap_in) {
                    cand_t.push(s.top);    // align: our top matches their top
                    cand_b.push(s.bottom); // align: our bottom matches theirs
                }
            }
            let (target_l, dist_l) = closest_target(r.left,   wa.left,   &cand_l);
            let (target_r, dist_r) = closest_target(r.right,  wa.right,  &cand_r);
            let (target_t, dist_t) = closest_target(r.top,    wa.top,    &cand_t);
            let (target_b, dist_b) = closest_target(r.bottom, wa.bottom, &cand_b);

            // Snap-in: window edge within snap_in px of the closest target
            // (monitor edge or a sibling window edge).
            // Snap-out: cursor has moved > snap_out px (Euclidean) from where
            // it was when the edge snapped. This makes diagonal drags release
            // corners just as easily as straight drags — the two axes no longer
            // need to independently exceed the threshold.
            let pt_l = SNAP_L.load(Ordering::Relaxed);
            let pt_r = SNAP_R.load(Ordering::Relaxed);
            let pt_t = SNAP_T.load(Ordering::Relaxed);
            let pt_b = SNAP_B.load(Ordering::Relaxed);

            // Clear release guards once the window edge has moved far enough away —
            // position-based so slow drags don't expire the guard too early.
            let snap_clear = snap_in * 2;
            if GUARD_L.load(Ordering::Relaxed) != 0 && dist_l > snap_clear { GUARD_L.store(0, Ordering::Relaxed); }
            if GUARD_R.load(Ordering::Relaxed) != 0 && dist_r > snap_clear { GUARD_R.store(0, Ordering::Relaxed); }
            if GUARD_T.load(Ordering::Relaxed) != 0 && dist_t > snap_clear { GUARD_T.store(0, Ordering::Relaxed); }
            if GUARD_B.load(Ordering::Relaxed) != 0 && dist_b > snap_clear { GUARD_B.store(0, Ordering::Relaxed); }

            let gd_l = GUARD_L.load(Ordering::Relaxed);
            let gd_r = GUARD_R.load(Ordering::Relaxed);
            let gd_t = GUARD_T.load(Ordering::Relaxed);
            let gd_b = GUARD_B.load(Ordering::Relaxed);

            let mut cur = POINT { x: 0, y: 0 };
            unsafe { GetCursorPos(&mut cur) };
            let cur_packed = pack_pt(cur.x, cur.y);

            macro_rules! check_edge {
                ($snap:expr, $snap_target:expr, $pt:expr, $guard:expr, $gd:expr, $dist:expr, $target:expr, $perp_disp:expr, $apply:expr) => {{
                    if $pt != i64::MIN {
                        // Release only on perpendicular movement — sliding along the
                        // edge contributes zero, so it can never accidentally loosen.
                        if $perp_disp > snap_out {
                            $snap.store(i64::MIN, Ordering::Relaxed);
                            $guard.store(1, Ordering::Relaxed);
                        } else {
                            // Reuse the target frozen at engage time, NOT a
                            // freshly recomputed one - see SNAP_TARGET_* doc.
                            let frozen = $snap_target.load(Ordering::Relaxed);
                            $apply(frozen);
                        }
                    } else if $gd == 0 && $dist <= snap_in {
                        $snap.store(cur_packed, Ordering::Relaxed);
                        $snap_target.store($target, Ordering::Relaxed);
                        $apply($target);
                    }
                }};
            }

            check_edge!(SNAP_L, SNAP_TARGET_L, pt_l, GUARD_L, gd_l, dist_l, target_l, x_disp(pt_l, cur.x), |t: i32| { r.left   = t; r.right  = t + width;  });
            check_edge!(SNAP_R, SNAP_TARGET_R, pt_r, GUARD_R, gd_r, dist_r, target_r, x_disp(pt_r, cur.x), |t: i32| { r.right  = t; r.left   = t - width;  });
            check_edge!(SNAP_T, SNAP_TARGET_T, pt_t, GUARD_T, gd_t, dist_t, target_t, y_disp(pt_t, cur.y), |t: i32| { r.top    = t; r.bottom = t + height; });
            check_edge!(SNAP_B, SNAP_TARGET_B, pt_b, GUARD_B, gd_b, dist_b, target_b, y_disp(pt_b, cur.y), |t: i32| { r.bottom = t; r.top    = t - height; });

            return 1; // TRUE
        }
        _ => {}
    }
    let orig = ORIG_WNDPROC.load(Ordering::SeqCst);
    unsafe { CallWindowProcW(orig, hwnd, msg, w, l) }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

pub fn install(
    on_enter: impl Fn() + Send + Sync + 'static,
    on_exit:  impl Fn() + Send + Sync + 'static,
) {
    if INSTALLED.swap(true, Ordering::SeqCst) { return; }
    let _ = ON_ENTER.set(Box::new(on_enter));
    let _ = ON_EXIT.set(Box::new(on_exit));

    std::thread::spawn(|| {
        for attempt in 0..50 {
            FOUND_HWND.store(0, Ordering::SeqCst);
            unsafe { EnumWindows(enum_cb, 0) };
            let hwnd = FOUND_HWND.load(Ordering::SeqCst);

            if hwnd != 0 {
                // Record our own hwnd + class name so the sibling-window
                // enumeration (for window-to-window snapping) can exclude
                // ourselves and recognise other MPV-NE windows by class.
                OWN_HWND.store(hwnd, Ordering::SeqCst);
                if let Some(class) = get_class_name(hwnd) {
                    let _ = OWN_CLASS.set(class);
                }
                // Replace WndProc with ours; save the original.
                let orig = unsafe { SetWindowLongPtrW(hwnd, GWLP_WNDPROC, wnd_proc as *const () as isize) };
                if orig != 0 {
                    ORIG_WNDPROC.store(orig, Ordering::SeqCst);
                    tracing::info!(hwnd, attempt, "modal hook: WndProc installed ok");
                    return;
                }
                tracing::warn!(hwnd, attempt, "modal hook: SetWindowLongPtrW failed, retrying");
            }
            std::thread::sleep(Duration::from_millis(100));
        }
        tracing::warn!("modal hook: gave up after 5s");
    });
}
